version: '2'
services:
    mongo:
        image: mongo
        ports:
            - 27017:27017
    web:
        image: node:6
        command: bash -c "sleep 2 && npm start" #wait 2 seconds for mongo
        environment:
            - MONGO_URI=mongodb://mongo/auth
            - SECRET=MyLocalSecretString
        env_file:
            - .env
        working_dir: /code
        volumes:
            - ./:/code
        ports:
            - 3000:3000
        depends_on:
            - mongo
        links:
            - mongo
